// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sunrise/liquiditypool/accumulator.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AccumulatorObject struct {
	Name        string                                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AccumValue  github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,2,rep,name=accum_value,json=accumValue,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"accum_value"`
	TotalShares cosmossdk_io_math.LegacyDec                 `protobuf:"bytes,3,opt,name=total_shares,json=totalShares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_shares"`
}

func (m *AccumulatorObject) Reset()         { *m = AccumulatorObject{} }
func (m *AccumulatorObject) String() string { return proto.CompactTextString(m) }
func (*AccumulatorObject) ProtoMessage()    {}
func (*AccumulatorObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_95374c39fefab413, []int{0}
}
func (m *AccumulatorObject) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccumulatorObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccumulatorObject.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccumulatorObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccumulatorObject.Merge(m, src)
}
func (m *AccumulatorObject) XXX_Size() int {
	return m.Size()
}
func (m *AccumulatorObject) XXX_DiscardUnknown() {
	xxx_messageInfo_AccumulatorObject.DiscardUnknown(m)
}

var xxx_messageInfo_AccumulatorObject proto.InternalMessageInfo

func (m *AccumulatorObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccumulatorObject) GetAccumValue() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.AccumValue
	}
	return nil
}

type AccumRecord struct {
	NumShares             cosmossdk_io_math.LegacyDec                 `protobuf:"bytes,1,opt,name=num_shares,json=numShares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"num_shares"`
	AccumValuePerShare    github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,2,rep,name=accum_value_per_share,json=accumValuePerShare,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"accum_value_per_share"`
	UnclaimedRewardsTotal github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,3,rep,name=unclaimed_rewards_total,json=unclaimedRewardsTotal,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"unclaimed_rewards_total"`
}

func (m *AccumRecord) Reset()         { *m = AccumRecord{} }
func (m *AccumRecord) String() string { return proto.CompactTextString(m) }
func (*AccumRecord) ProtoMessage()    {}
func (*AccumRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_95374c39fefab413, []int{1}
}
func (m *AccumRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccumRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccumRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccumRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccumRecord.Merge(m, src)
}
func (m *AccumRecord) XXX_Size() int {
	return m.Size()
}
func (m *AccumRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AccumRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AccumRecord proto.InternalMessageInfo

func (m *AccumRecord) GetAccumValuePerShare() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.AccumValuePerShare
	}
	return nil
}

func (m *AccumRecord) GetUnclaimedRewardsTotal() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.UnclaimedRewardsTotal
	}
	return nil
}

func init() {
	proto.RegisterType((*AccumulatorObject)(nil), "sunrise.liquiditypool.AccumulatorObject")
	proto.RegisterType((*AccumRecord)(nil), "sunrise.liquiditypool.AccumRecord")
}

func init() {
	proto.RegisterFile("sunrise/liquiditypool/accumulator.proto", fileDescriptor_95374c39fefab413)
}

var fileDescriptor_95374c39fefab413 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xbf, 0x6e, 0xd4, 0x40,
	0x10, 0xc6, 0x6f, 0x73, 0x08, 0x29, 0x7b, 0x34, 0xac, 0x38, 0x71, 0x0a, 0xc8, 0x17, 0x85, 0x82,
	0x48, 0x88, 0x5d, 0x85, 0x88, 0x07, 0xe0, 0x88, 0xa8, 0x90, 0x82, 0x0c, 0xa2, 0xa0, 0xb1, 0xd6,
	0xeb, 0x91, 0x6f, 0x89, 0xd7, 0x6b, 0xf6, 0x4f, 0xc0, 0x3d, 0x0d, 0x1d, 0xcf, 0xc1, 0x93, 0xa4,
	0x4c, 0x89, 0x28, 0x02, 0x3a, 0xf3, 0x20, 0xc8, 0xbb, 0x3e, 0x12, 0xa8, 0xd2, 0x5c, 0xe5, 0xb1,
	0xf6, 0x9b, 0xdf, 0xf7, 0xcd, 0x68, 0xf0, 0x43, 0xeb, 0x6b, 0x23, 0x2d, 0xb0, 0x4a, 0x7e, 0xf0,
	0xb2, 0x90, 0xae, 0x6d, 0xb4, 0xae, 0x18, 0x17, 0xc2, 0x2b, 0x5f, 0x71, 0xa7, 0x0d, 0x6d, 0x8c,
	0x76, 0x9a, 0x4c, 0x07, 0x21, 0xfd, 0x47, 0xb8, 0x73, 0xa7, 0xd4, 0xa5, 0x0e, 0x0a, 0xd6, 0x57,
	0x51, 0xbc, 0x93, 0x08, 0x6d, 0x95, 0xb6, 0x2c, 0xe7, 0x16, 0xd8, 0xe9, 0x41, 0x0e, 0x8e, 0x1f,
	0x30, 0xa1, 0x65, 0x1d, 0xdf, 0xf7, 0x3a, 0x84, 0x6f, 0x3f, 0xbb, 0xb4, 0x38, 0xce, 0xdf, 0x83,
	0x70, 0x84, 0xe0, 0x1b, 0x35, 0x57, 0x30, 0x43, 0xbb, 0x68, 0x7f, 0x3b, 0x0d, 0x35, 0x31, 0x78,
	0x12, 0xb2, 0x64, 0xa7, 0xbc, 0xf2, 0x30, 0xdb, 0xda, 0x1d, 0xef, 0x4f, 0x9e, 0xdc, 0xa7, 0x91,
	0x4f, 0x7b, 0x3e, 0x1d, 0xf8, 0xf4, 0x08, 0xc4, 0x73, 0x2d, 0xeb, 0xc5, 0xe1, 0xd9, 0xc5, 0x7c,
	0xf4, 0xed, 0xe7, 0xfc, 0x51, 0x29, 0xdd, 0xd2, 0xe7, 0x54, 0x68, 0xc5, 0x86, 0x3c, 0xf1, 0xf3,
	0xd8, 0x16, 0x27, 0xcc, 0xb5, 0x0d, 0xd8, 0x75, 0x8f, 0x4d, 0x71, 0x70, 0x79, 0xdb, 0x9b, 0x90,
	0x17, 0xf8, 0x96, 0xd3, 0x8e, 0x57, 0x99, 0x5d, 0x72, 0x03, 0x76, 0x36, 0xee, 0xf3, 0x2c, 0x1e,
	0xf4, 0xd8, 0x1f, 0x17, 0xf3, 0x7b, 0x11, 0x62, 0x8b, 0x13, 0x2a, 0x35, 0x53, 0xdc, 0x2d, 0xe9,
	0x4b, 0x28, 0xb9, 0x68, 0x8f, 0x40, 0xa4, 0x93, 0xd0, 0xf8, 0x3a, 0xf4, 0xed, 0xfd, 0xde, 0xc2,
	0x93, 0x30, 0x65, 0x0a, 0x42, 0x9b, 0x82, 0x2c, 0x30, 0xae, 0xbd, 0x5a, 0x53, 0xd1, 0xf5, 0xa9,
	0xdb, 0xb5, 0x57, 0x91, 0x49, 0x3e, 0x23, 0x3c, 0xbd, 0xb2, 0x90, 0xac, 0x01, 0x13, 0x81, 0x9b,
	0x5b, 0x0d, 0xb9, 0x5c, 0xcd, 0x2b, 0x30, 0x21, 0x07, 0xf9, 0x82, 0xf0, 0x5d, 0x5f, 0x8b, 0x8a,
	0x4b, 0x05, 0x45, 0x66, 0xe0, 0x23, 0x37, 0x85, 0xcd, 0xc2, 0xf0, 0xb3, 0xf1, 0xa6, 0x82, 0x4c,
	0xff, 0x3a, 0xa6, 0xd1, 0xf0, 0x4d, 0xef, 0xb7, 0x38, 0x3e, 0x5b, 0x25, 0xe8, 0x7c, 0x95, 0xa0,
	0x5f, 0xab, 0x04, 0x7d, 0xed, 0x92, 0xd1, 0x79, 0x97, 0x8c, 0xbe, 0x77, 0xc9, 0xe8, 0xdd, 0xd3,
	0x2b, 0xf4, 0xe1, 0x7c, 0x2b, 0xde, 0x82, 0x59, 0xff, 0xb0, 0x4f, 0xff, 0x9d, 0x7d, 0x30, 0xcc,
	0x6f, 0x86, 0x23, 0x3d, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xe3, 0x20, 0xdd, 0x1c, 0x03,
	0x00, 0x00,
}

func (m *AccumulatorObject) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccumulatorObject) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccumulatorObject) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalShares.Size()
		i -= size
		if _, err := m.TotalShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAccumulator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.AccumValue) > 0 {
		for iNdEx := len(m.AccumValue) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccumValue[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccumulator(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintAccumulator(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AccumRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccumRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccumRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UnclaimedRewardsTotal) > 0 {
		for iNdEx := len(m.UnclaimedRewardsTotal) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UnclaimedRewardsTotal[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccumulator(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.AccumValuePerShare) > 0 {
		for iNdEx := len(m.AccumValuePerShare) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccumValuePerShare[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccumulator(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size := m.NumShares.Size()
		i -= size
		if _, err := m.NumShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAccumulator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintAccumulator(dAtA []byte, offset int, v uint64) int {
	offset -= sovAccumulator(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AccumulatorObject) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovAccumulator(uint64(l))
	}
	if len(m.AccumValue) > 0 {
		for _, e := range m.AccumValue {
			l = e.Size()
			n += 1 + l + sovAccumulator(uint64(l))
		}
	}
	l = m.TotalShares.Size()
	n += 1 + l + sovAccumulator(uint64(l))
	return n
}

func (m *AccumRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NumShares.Size()
	n += 1 + l + sovAccumulator(uint64(l))
	if len(m.AccumValuePerShare) > 0 {
		for _, e := range m.AccumValuePerShare {
			l = e.Size()
			n += 1 + l + sovAccumulator(uint64(l))
		}
	}
	if len(m.UnclaimedRewardsTotal) > 0 {
		for _, e := range m.UnclaimedRewardsTotal {
			l = e.Size()
			n += 1 + l + sovAccumulator(uint64(l))
		}
	}
	return n
}

func sovAccumulator(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAccumulator(x uint64) (n int) {
	return sovAccumulator(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AccumulatorObject) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccumulator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccumulatorObject: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccumulatorObject: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccumulator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccumulator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccumulator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccumValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccumulator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccumulator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccumulator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccumValue = append(m.AccumValue, types.DecCoin{})
			if err := m.AccumValue[len(m.AccumValue)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccumulator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccumulator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccumulator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccumulator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccumulator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccumRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccumulator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccumRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccumRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccumulator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccumulator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccumulator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NumShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccumValuePerShare", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccumulator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccumulator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccumulator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccumValuePerShare = append(m.AccumValuePerShare, types.DecCoin{})
			if err := m.AccumValuePerShare[len(m.AccumValuePerShare)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnclaimedRewardsTotal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccumulator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccumulator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccumulator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnclaimedRewardsTotal = append(m.UnclaimedRewardsTotal, types.DecCoin{})
			if err := m.UnclaimedRewardsTotal[len(m.UnclaimedRewardsTotal)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccumulator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccumulator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAccumulator(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAccumulator
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccumulator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccumulator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAccumulator
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAccumulator
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAccumulator
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAccumulator        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAccumulator          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAccumulator = fmt.Errorf("proto: unexpected end of group")
)
